# Generated by Django 3.0.6 on 2020-05-30 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='estudiante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('est_cod', models.IntegerField()),
                ('est_nom', models.CharField(max_length=20)),
                ('est_ap', models.CharField(max_length=20)),
                ('est_cur', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='materia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ma_cod', models.IntegerField()),
                ('ma_nom', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='profesor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pro_cod', models.IntegerField()),
                ('pro_nom', models.CharField(max_length=20)),
                ('pro_ap', models.CharField(max_length=20)),
                ('pro_are', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='salones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sal_cod', models.IntegerField()),
                ('sal_nom', models.CharField(max_length=20)),
                ('sal_cur', models.CharField(max_length=20)),
            ],
        ),
    ]
